openapi: 3.0.0
info:
  title: OTUS Highload Architect
  version: 1.2.0
paths:
  /dialog/{user_id}/unread:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIDHeader'
        - name: user_id
          schema:
            $ref: '#/components/schemas/UserId'
          required: true
          in: path
      responses:
        '200':
          description: Кол
          content:
            application/json:
              schema:
                type: integer
                description: Кол-во непрочитанных сообщений в диалоге
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/5xx'
        '503':
          $ref: '#/components/responses/5xx'

components:
  parameters:
    UserIDHeader:
      name: X-User-Id
      in: header
      description: Идентификатор пользователя
      required: true
      schema:
        type: string
  responses:
    '400':
      description: Невалидные данные ввода
    '401':
      description: Неавторизованный доступ
    5xx:
      description: Ошибка сервера
      headers:
        Retry-After:
          description: Время, через которое еще раз нужно сделать запрос
          required: false
          schema:
            type: integer
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: Описание ошибки
              request_id:
                type: string
                description: >-
                  Идентификатор запроса. Предназначен для более быстрого поиска
                  проблем.
              code:
                type: integer
                description: >-
                  Код ошибки. Предназначен для классификации проблем и более
                  быстрого решения проблем.
  schemas:
    UserId:
      type: string
      description: Идентификатор пользователя



